### ISSUE TITLE
Can't create call offer when mode=flash

### ISSUE THREAD

**Issue by Luciuz** [voximplant/videochat#1]
Demo console:

onSDKReady version 2.9.13866
WebRTC supported: false
Establishing connection...
Mic/Cam access allowed: true
Connection established: true
client@videochat.director.voximplant.com
AuthResult: true
Calling to server
CallFailed: 9d2729bc048114c5 code: 406 reason: Not Acceptable

**Comment by voximplant** [comment]
VoxEngine.forwardCallToUserDirect(); works only for WebRTC mode. For Flash to Flash calls you need to use VoxEngine.forwardCallToUser(null, true);

**Comment by Luciuz** [comment]
Many thanks

**Comment by Luciuz** [comment]
Nothing changes(

**Comment by voximplant** [comment]
You need to remove `{"X-DirectCall": "true"}` from JS on the client:
`outboundCall = currentCall = voxAPI.call(document.getElementById('phonenum').value, true, "TEST CUSTOM DATA", {"X-DirectCall": "true"});`

**Comment by Luciuz** [comment]
ty
