### ISSUE TITLE
Не работает с Flash

### ISSUE THREAD

**Issue by K3ler** [voximplant/videochat#2]
Попробовал, сделать как описано в примере, но почему-то когда подгружается Flash, все зависает в firefox. Но по WebRTC все работает хорошо. Может я что-то не то сделал, раз флеш есть в конфинге WebSDK?

**Comment by aylarov** [comment]
А зачем вы используете Flash в Firefox? :) Без дополнительной информации сложно сказать, что именно происходит, можете написать на support@voximplant.com
