### ISSUE TITLE
Call Failed 406 reason: Not Acceptable

### ISSUE THREAD

**Issue by egrish** [voximplant/videochat#3]
Сделал все, как было написано. Залогигнился 2-мя пользователями с 2-х разных машин.
При звонки показывает вот такую ошибку:

CallFailed: ca1a558b311193ea code: 406 reason: Not Acceptable

**Comment by aylarov** [comment]
Эта ошибка возникает случае если у вас или не указан хедер X-DirectCall: true или неверный сценарий, должен быть VoxEngine.forwardCallToUserDirect()

**Comment by egrish** [comment]
Я делаю все по инструкциию В сценарии указан VoxEngine.forwardCallToUserDirect();.
Как указать заголовок X-DirectCall ?

**Comment by egrish** [comment]
Заголовок X-DirectCall  указан в вашем же приложении при вызове звонка.

**Comment by aylarov** [comment]
В каком браузере вы пытаетесь совершить звонок?

**Comment by egrish** [comment]
Safari vs IE 11

**Comment by aylarov** [comment]
В случае Flash peer-to-peer звонки недоступны, это работает только при использовании WebRTC.
