### ISSUE TITLE
microphone/camera not working for server ip 

### ISSUE THREAD

**Issue by nagashreeckn** [voximplant/videochat#5]
Hi,
i have hosted videochat in server. i am accessing from my local that application in browser. its giving issue "You have to allow access to your microphone to use the service".

How allow microphone/camera access if the application running in server?

Please help me to sort out this issue

**Comment by irbisadm** [comment]
Hi,
do you have https in your server?

**Comment by nagashreeckn** [comment]
no i am not using https

**Comment by irbisadm** [comment]
Sorry, but most browsers deny media access for insecure origin. For test reason, you can use Firefox.
